---
- name: Backup TEDs
  hosts: TED
  gather_facts: yes
  collections:
   - fortinet.fortios
   
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
   
  tasks:
  - name: asdad
    ansible.builtin.debug:
      var: hostvars[inventory_hostname]
      
  - name: Backup?
    fortios_monitor:
     selector: 'backup.system.config'
     vdom: 'root'
     params:
         scope: 'global'
    register: backupinfo

  - name: Save the backup information.
    copy:
     content: '{{ backupinfo.meta.raw }}'
     dest: './local.backup'

#  - name: Get uptime information
#    ansible.builtin.shell: scp -o StrictHostKeyChecking=no ./local.backup technoma@rhsat.technoma.local:/home/technoma
#    expect: "technoma@rhsat.technoma.local's password:"
#    send: "callTechnoma*911\n"

#  - name: copy file from local to machine2
#    shell: scp -o StrictHostKeyChecking=no ./local.backup technoma@rhsat.technoma.local:/home/technoma
#    expect: "technoma@rhsat.technoma.local's password:"
#    send: "callTechnoma*911\n"
  
  - name: Copy?
    ansible.builtin.expect:
      command: scp -o StrictHostKeyChecking=no ./local.backup technoma@rhsat.technoma.local:/home/technoma
      responses:
        (?i)password: "callTechnoma*911"
  # you don't want to show passwords in your logs
    no_log: true
    
#  - name: Get uptime information
#    ansible.builtin.shell: ls -l .
#    register: result

#  - name: Print return information from the previous task
#    ansible.builtin.debug:
#      var: result
