---
- name: Backup TEDs
  hosts: TED
  gather_facts: yes
  collections:
   - fortinet.fortios
   
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
   
  tasks:
  - name: Backup?
    fortios_configuration_fact:
      vdom:  "{{ vdom }}"
      system_global:
        selector: firewall_address
