---
- name: Backup TEDs
  hosts: TED
  gather_facts: yes
  collections:
   - fortinet.fortios
   
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
   
  tasks:
  - name: Backup?
    fortios_monitor:
     selector: 'backup.system.config'
     vdom: 'root'
     params:
         scope: 'global'
    register: backupinfo

  - name: Save the backup information.
    copy:
     content: '{{ backupinfo.meta.raw }}'
     dest: './local.backup'

  - name: copy file from local to machine2
    shell: scp -o StrictHostKeyChecking=no ./local.backup technoma@rhsat.technoma.local:/home/technoma
    expect: "technoma@rhsat.technoma.local's password:"
    send: "callTechnoma*911\n"
  
  - name: Get uptime information
    ansible.builtin.shell: ls -l .
    register: result

  - name: Print return information from the previous task
    ansible.builtin.debug:
      var: result
