---
- name: Backup TEDs
  hosts: TEDs
  gather_facts: yes
  collections:
   - fortinet.fortios
   
  connection: httpapi
  vars:
   vdom: "root"
   serv: "rhsat.technoma.local"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 20443
   
  tasks:
  - name: Extraccion de hostname del dispositivo.
    fortios_monitor_fact:
     selector: 'system_status'
     formatters:
       - hostname
     vdom: 'root'
    register: status
    
  #- name: print status
  #  ansible.builtin.debug:
  #    var: status["meta"]["results"]["hostname"]
  
  # Copia el backup a un registro.
  - name: Generando backup.
    fortios_monitor:
     selector: 'backup.system.config'
     vdom: 'root'
     params:
         scope: 'global'
    register: backupinfo

  # Guarda el registro en un archivo.
  - name: Guardando backup.
    copy:
     content: '{{ backupinfo.meta.raw }}'
     dest: './{{ status["meta"]["results"]["hostname"] }}.conf'
  
  - name: Creando carpeta (Si todavia no existe).
    ansible.builtin.expect:
      command: ssh -o StrictHostKeyChecking=no technoma@{{ serv }} "mkdir -p ./{{ status["meta"]["results"]["hostname"] }} #Agregar IP
      responses:
        (?i)password: "callTechnoma*911"
  # you don't want to show passwords in your logs
    no_log: true
    
  - name: Subiendo backup al repo.
    ansible.builtin.expect:
      command: scp -o StrictHostKeyChecking=no ./{{ status["meta"]["results"]["hostname"] }}.conf technoma@{{ serv }}:/home/technoma/{{ status["meta"]["results"]["hostname"] }}/{{ ansible_date_time["date"] }}-{{ status["meta"]["results"]["hostname"] }}.conf
      responses:
        (?i)password: "callTechnoma*911"
  # you don't want to show passwords in your logs
    no_log: true

#  - name: Print return information from the previous task
#    ansible.builtin.debug:
#      var: result
