---
- name: Playbook to handle users
  hosts: Lab
  become: true
  collections:
    - freeipa.ansible_freeipa

  tasks:
  # Ensure user pinky is present
  - name: Crear usuario.
    ipauser:
      ipaadmin_password: techadmin1234
      name: "{{ username }}"
      first: "{{ nombre }}"
      last: "{{ apellido }}"
      #uid: 10001
      gid: 1890400000
      phone: "+555123457"
      email: pinky@acme.com
      passwordexpiration: "2023-01-19 23:59:59"
      password: "no-brain"
      update_password: on_create

#   - name: Convertir pinky en admin.
#    ipasudorule:
#      ipaadmin_password: techadmin1234
#      name: test
#      user: pinky
