---
- name: Configuracion de TED
  hosts: TED
  gather_facts: yes
  collections:
   - fortinet.fortios
   
  connection: httpapi
  vars:
   vdom: "root"
   snmpmanager: "172.22.22.246"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
   
  tasks:
  - name: Configuraci贸n de atributos globales.
    fortios_system_global:
      vdom:  "{{ vdom }}"
      system_global:
        admin_ssh_port: 2222
        admin_telnet_port: 2323
        admintimeout: 30
        hostname: "{{ hostname }}"
        timezone: 87
        
  - name: Configuraci贸n de SNMP.
    fortios_system_snmp_community:
      vdom:  "{{ vdom }}"
      state: "present"
      system_snmp_community:
        name: "T3chn0m4"
        id: "1"
        hosts:
          -
            ip: "{{ snmpmanager }}"
            id: "1"
        events: "cpu-high,mem-low,log-full,intf-ip,vpn-tun-up,vpn-tun-down,ha-switch,ha-hb-failure,ips-signature,ips-anomaly,av-virus,av-oversize,av-pattern,av-fragmented,fm-if-change,fm-conf-change,bgp-established,bgp-backward-transition,ha-member-up,ha-member-down,ent-conf-change,av-conserve,av-bypass,av-oversize-passed,av-oversize-blocked,ips-pkg-update,ips-fail-open,temperature-high,voltage-alert,power-supply-failure,faz-disconnect,wc-ap-up,wc-ap-down,fswctl-session-up,fswctl-session-down,load-balance-real-server-down,device-new,per-cpu-high,dhcp,ospf-nbr-state-change,ospf-virtnbr-state-change"
        query_v1_status: "disable"
        trap_v1_status: "disable"

  #- name: Creaci贸n de usuarios.
  #  fortios_system_admin:
  #    vdom:  "{{ vdom }}"
  #    state: "present"
  #    system_admin:
  #      accprofile: "super_admin"
  #      name: "technoma"
  #      password: "callTechnoma*911"
        
  - name: Configuraci贸n de interfaces.
  #  fortios_system_virtual_switch:
  #    vdom:  "{{ vdom }}"
  #    state: "present"
  #    member_path: "port:name"
  #    member_state: "absent"
  #    system_virtual_switch:
  #      name: "lan"
  #      port:
  #        -
  #          name: "lan1"
    fortios_system_interface:
      - name: "WAN"
        vdom:  "{{ vdom }}"
        state: "present"
          system_interface:
            name: "wan"
            mode: "static"
            ip: "10.53.{{ num }}.2/30"
            allowaccess: "ping,https,ssh,http"
            alias: "Ufinet"
            lldp_reception: "enable"
            role: "wan"
      - name: "10"
        vdom:  "{{ vdom }}"
        state: "present"
          system_interface:
            name: "VLAN 10"
            ip: "10.50.{{ num }}.1/28"
            allowaccess: "ping,https,ssh,http"
            alias: "TED"
            device_identification: "enable"
            role: "lan"
            interface: "lan1"
            vlanid: "10"
