---
- name: Do something
  hosts: LabGroup
  gather_facts: yes
  collections:
   - fortinet.fortios
   
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 3443
  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      vdom:  "{{ vdom }}"
      system_global:
        admintimeout: "60"
        hostname: "FG-ANSIBLE-TEST"
