---
- name: Do something
  hosts: LabGroup
  gather_facts: no
  collections:
   - fortinet.fortios


  vars:
   vdom: "root"
   
  tasks:
  - debug:
        msg: "Trying to do something"

  - name: Display information about the top CPU processes.
    fortios_system_performance_top:
      vdom:  "{{ vdom }}"
      system_performance_top:
        <delay>: "1"
